export const kingdomList = {
  basic: [
    { name: "冒険者" },
    { name: "役人" },
    { name: "地下貯蔵庫" },
    { name: "礼拝堂" },
    { name: "議事堂" },
    { name: "祝祭" },
    { name: "庭園" },
    { name: "研究所" },
    { name: "書庫" },
    { name: "市場" },
    { name: "民兵" },
    { name: "鉱山" },
    { name: "堀" },
    { name: "金貸し" },
    { name: "改築" },
    { name: "鍛冶屋" },
    { name: "玉座の間" },
    { name: "村" },
    { name: "魔女" },
    { name: "工房" },
    { name: "職人" },
    { name: "山賊" },
    { name: "前駆者" },
    { name: "商人" },
    { name: "密猟者" },
    { name: "衛兵" },
    { name: "家臣" }
  ],
  nocturne: [
    { name: "詩人" },
    { name: "恵みの村" },
    { name: "墓地" },
    { name: "取り替え子" },
    { name: "カブラー" },
    { name: "コンクラーベ" },
    { name: "納骨堂" },
    { name: "呪われた村" },
    { name: "悪人のアジト" },
    { name: "悪魔の工房" },
    { name: "ドルイド" },
    { name: "悪魔祓い" },
    { name: "忠犬" },
    { name: "愚者" },
    { name: "ゴーストタウン" },
    { name: "守護者" },
    { name: "偶像" },
    { name: "レプラコーン" },
    { name: "修道院" },
    { name: "ネクロマンサー" },
    { name: "夜警" },
    { name: "ピクシー" },
    { name: "プーカ" },
    { name: "夜襲" },
    { name: "聖なる木立ち" },
    { name: "秘密の洞窟" },
    { name: "羊飼い" },
    { name: "暗躍者" },
    { name: "迫害者" },
    { name: "追跡者" },
    { name: "悲劇のヒーロー" },
    { name: "吸血鬼" },
    { name: "人狼" }
  ]
};

export const nameMap = { basic: "基本", nocturne: "夜想曲" };
